CREATE ROLE c##RAdmin;

GRANT CONNECT TO c##RAdmin;
GRANT CREATE SESSION TO c##RAdmin;
GRANT DBA TO c##RAdmin;

CREATE ROLE c##RCustomer;

GRANT CONNECT TO c##RCustomer;
GRANT CREATE SESSION TO c##RCustomer;
GRANT SELECT ON ITEM TO c##RCustomer;
GRANT SELECT, INSERT, DELETE ON ORDERS TO c##RCustomer;

CREATE ROLE c##RGuest;

GRANT CONNECT TO c##RGuest;
GRANT CREATE SESSION TO c##RGuest;
GRANT SELECT ON ITEM TO c##RGuest;

CREATE ROLE c##RManager;

GRANT CONNECT TO c##RManager;

GRANT CREATE SESSION TO c##RManager;
GRANT SELECT, INSERT, UPDATE, DELETE ON ITEM TO c##RManager;
GRANT SELECT, INSERT, UPDATE, DELETE ON ORDERS TO c##RManager;