-- USERGROUP Table
CREATE TABLE USERGROUP (
    UserID NUMBER PRIMARY KEY,
    Email VARCHAR2(100),
    USERNAME VARCHAR2(50),
    GENDER CHAR(1),
    ADDRESS VARCHAR2(255),
    PHONENUM VARCHAR2(15),
    ISMANAGER CHAR(1) CHECK (ISMANAGER IN ('Y', 'N'))
);

-- DELIVERYADDRESS Table
CREATE TABLE DELIVERYADDRESS (
    AddressID NUMBER PRIMARY KEY,
    UserID NUMBER,
    FullName VARCHAR2(100),
    Phone VARCHAR2(15),
    DetailAddress VARCHAR2(255),
    Ward VARCHAR2(50),
    District VARCHAR2(50),
    City VARCHAR2(50),
    Province VARCHAR2(50),
    FOREIGN KEY (UserID) REFERENCES USERGROUP(UserID) ON DELETE CASCADE
);

-- ORDERS Table
CREATE TABLE Orders (
    OrderID NUMBER PRIMARY KEY,
    UserID NUMBER,
    OrderDate DATE,
    StatusCode NUMBER DEFAULT 3 NOT NULL,
    TotalPrice NUMBER(10, 2) DEFAULT 0,
    FOREIGN KEY (UserID) REFERENCES USERGROUP(UserID) ON DELETE CASCADE,
    CONSTRAINT CHK_StatusCode CHECK (StatusCode IN (-1, 0, 1, 2, 3))
);

-- ITEM Table
CREATE TABLE Item (
    ItemID NUMBER PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Price NUMBER(10, 2),
    Stock NUMBER,
    Description VARCHAR2(4000)
);

-- TOYS Table
CREATE TABLE Toys (
    ItemID NUMBER PRIMARY KEY,
    ProductionDate DATE,
    Manufacturer VARCHAR2(100),
    FOREIGN KEY (ItemID) REFERENCES Item(ItemID) ON DELETE CASCADE
);

-- BOOK Table
CREATE TABLE Book (
    ItemID NUMBER PRIMARY KEY,
    ISBN VARCHAR2(20),
    PublicationDate DATE,
    FOREIGN KEY (ItemID) REFERENCES Item(ItemID) ON DELETE CASCADE
);

-- BOOKGENRE Table
CREATE TABLE BookGenre (
    BookID NUMBER NOT NULL,
    Genre VARCHAR2(50) NOT NULL,
    PRIMARY KEY (BookID, Genre),
    FOREIGN KEY (BookID) REFERENCES Book(ItemID) ON DELETE CASCADE
);

-- AUTHOR Table
CREATE TABLE Author (
    AuthorID NUMBER PRIMARY KEY,
    FullName VARCHAR2(100),
    Bio VARCHAR2(255)
);

-- WRITES Table
CREATE TABLE Writes (
    AuthorID NUMBER,
    ItemID NUMBER,
    PRIMARY KEY (AuthorID, ItemID),
    FOREIGN KEY (AuthorID) REFERENCES Author(AuthorID) ON DELETE CASCADE,
    FOREIGN KEY (ItemID) REFERENCES Book(ItemID) ON DELETE CASCADE
);

-- PUBLISHER Table
CREATE TABLE Publisher (
    PublisherID NUMBER PRIMARY KEY,
    Name VARCHAR2(100),
    Address VARCHAR2(255),
    ContactInfo VARCHAR2(100)
);

-- PUBLISHES Table
CREATE TABLE Publishes (
    PublisherID NUMBER,
    ItemID NUMBER,
    PRIMARY KEY (PublisherID, ItemID),
    FOREIGN KEY (PublisherID) REFERENCES Publisher(PublisherID) ON DELETE CASCADE,
    FOREIGN KEY (ItemID) REFERENCES Book(ItemID) ON DELETE CASCADE
);

-- ORDERITEM Table
CREATE TABLE OrderItem (
    OrderID NUMBER,
    ItemID NUMBER,
    Quantity NUMBER,
    PRIMARY KEY (OrderID, ItemID),
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE,
    FOREIGN KEY (ItemID) REFERENCES Item(ItemID) ON DELETE CASCADE
);

-- ITEMIMAGES Table
CREATE TABLE ItemImages (
    ImageID NUMBER PRIMARY KEY,
    ItemID NUMBER NOT NULL,
    FOREIGN KEY (ItemID) REFERENCES Item(ItemID) ON DELETE CASCADE
);

